### ISSUE TITLE
Unacceptable performance issues when form fields are displayed by dedicated Backbone views

### ISSUE THREAD

**Issue by jrwdunham** [jrwdunham/dative#104]
@cesine any ideas on why this would be? See f4b0431956331f3f2aab3b7fdfa696f21ff049fa.

Checkout the above-referenced commit and try browsing 25 or more forms and you'll see that the app is very unresponsive. My initial tests show that these "field display" views are being correctly destroyed and unbound so memory leaks due to zombie views shouldn't be an issue here...

**Comment by jrwdunham** [comment]
As the branch state of the project should indicate, I have reverted the master branch to the state before these "field display" views were created. The "field-displays-are-views" branch now houses the experiment in using Backbone subviews for all field displays.

Using Backbone subviews for everything results in much cleaner, more modular, and more configurable code so I would like to return to this strategy. However, for the time being I'm returning to and will continue developing via the older strategy where the `FormView` handles the displaying of its fields all on its own.

**Comment by jrwdunham** [comment]
See http://addyosmani.com/blog/performance-optimisation-with-timeline-profiles/ fer lernin how better faster make

**Comment by cesine** [comment]
i think you can run a similar test in the prototype backbone app (each field is a backbone view too) if you set the number of visible datum to 25...  maybe you will find something by doing the comparison... i think its pretty slow too in the prototype app

**Comment by jrwdunham** [comment]
In the latest branch I have decided to just swallow this performance hit. We can work on improving it later, perhaps by instantiating and rendering fewer sub-views (with user configuration) and instantiating/rendering them as needed when needed ...
