### ISSUE TITLE
perfect scollbar is missing in travis build

### ISSUE THREAD

**Issue by cesine** [jrwdunham/dative#113]
Running "requirejs:dist" (requirejs) task
>> Error: Error: ENOENT, no such file or directory '/home/travis/build/jrwdunham/dative/.tmp/bower_components/perfect-scrollbar/src/perfect-scrollbar.js'
>> In module tree:
>>     main
>>       views/app
>>         views/help-dialog
Warning: Task "requirejs:dist" failed. Use --force to continue.

**Comment by cesine** [comment]
@jrwdunham i emerged from editing the psycholing dash, i tried looking at what was going on with travis on you rmaster, and this is the error i have. considering i have a bunch of pull requests with travis, it would be easier to get those merged before i work on this..

**Comment by jrwdunham** [comment]
Hey, yeah, I've stopped using "perfect scrollbar" (not perfect). We need to purge it throughout the code. Pull requests first though, I'm working on that ...
