### ISSUE TITLE
Consider using 16px font throughout Dative

### ISSUE THREAD

**Issue by jrwdunham** [jrwdunham/dative#72]
http://www.smashingmagazine.com/2011/10/07/16-pixels-body-copy-anything-less-costly-mistake/

**Comment by cesine** [comment]
consider using em (not px) 

http://stackoverflow.com/questions/609517/why-em-instead-of-px

**Comment by jrwdunham** [comment]
Yes, using em (or %) seems to be best practice. I just mean that the default font size should probably be larger than it currently is.

**Comment by jrwdunham** [comment]
Font size has been increased to reasonable levels, I think.
