### ISSUE TITLE
Make `grunt build` and `grunt serve:dist` work!

### ISSUE THREAD

**Issue by jrwdunham** [jrwdunham/dative#84]
There are a number of issues:

1. current build configuration expects app/scripts/jquery-extensions/superclick.js to be present in dist/scripts/jquery-extensions. There is a file there but it's empty. But even if the file were there and had content, it should be ugli/minified with the rest of the js stuff (shouldn't it?)

2. something is going wrong with the font-awesome css. The 'build' task isn't dealing with this properly.

3. my logic for dynamically changing the jQueryUI theme is being broken by the CSS concatenation. Theme-changing depends on there being two <link> elements  (with specific ids) in index.html:

    <link id="font-awesome-css" rel="stylesheet" href="styles/font-awesome-4.2.0/css/font-awesome.css">
    <link id="jquery-ui-css" rel="stylesheet" href="bower_components/jqueryui/themes/cupertino/jquery-ui.css">

**Comment by jrwdunham** [comment]
The font awesome problem involves the fact that the font-awesome.css is present in the minified main.css, but the fonts are not being copied over to dist/.

**Comment by cesine** [comment]
i was trying to work on this today, and i came up with a seperate question.

do we want to use bower to manage dependancies like superclick? if yes i will make a pull request that moves these deps into bower management, and then work on this..

**Comment by jrwdunham** [comment]
If bowerifying superclick/fish is possible and it works, then yes, I would prefer it... (What are the drawbacks?)

**Comment by cesine** [comment]
it looks like just using the bower versions made it possible to run grunt serve:dist without any more errors (just the font awesome error, which i will work on now)

**Comment by jrwdunham** [comment]
awesome! 

Not sure if it's relevant for the build, but you may want to be aware that app/styles/fonts/ now exists: it has the SIL gentium web fonts in there...

**Comment by cesine** [comment]
i saw those, looks okay. i think i finished playing with this, sending you a PR..

you have to check the superfish css changes because the superfish css you had is not hte same version as the superfish css that is with the superfish version you had, it hink its working but i dont know the app very well to judge if the css is wierd
