### ISSUE TITLE
dont download all the data, only what the user wants to see

### ISSUE THREAD

**Issue by cesine** [jrwdunham/dative#93]
to start you can just load the 10 most recently modified datum (this is what the prototype did)

**Comment by jrwdunham** [comment]
I'm closing this issue and moving the discussion over to #97 since they are essentially the same issue (imo).

**Comment by cesine** [comment]
this was a more general issue about avoiding downloading data that the user doesn't want to see. 

as an example: we had this problem with the spreadsheet which dative was following because the title of a users corpora were not saved in the user, so you were requesting the corpus details for every one of their corpora, which causes corpora that the user has no intention of opening to be re-indexed again. this was fixed in the commonjs so hopefully you can use it too, if the opens a corpus, its title and descriptino will get cached in the connection which is stored in the user's corpora so we dont need to make erver requests for the titles. https://github.com/OpenSourceFieldlinguistics/FieldDB/blob/master/api/corpus/Connection.js#L264

maybe htere are other examples where we are making requests which arent necesary? i'm not sure but maybe you can think of other cases in the code. one might be when do you request team members? when you load a corpus.. or only when the user has the intention of changing the team members.
