### ISSUE TITLE
Tags library

### ISSUE THREAD

**Issue by cesine** [jrwdunham/dative#98]
josh used magicsuggest

he did a prototype in here:
https://github.com/OpenSourceFieldlinguistics/FieldDBGlosser/tree/master/client/jquery

this is one of the screenshots
https://github.com/OpenSourceFieldlinguistics/FieldDB/issues/1141

![glosser_ui4](https://f.cloud.github.com/assets/760694/2366359/b4f2eb28-a6fe-11e3-8cbd-d438202f8745.png)

**Comment by jrwdunham** [comment]
Tags implemented with a working design now.
